### ISSUE TITLE
Version role in galaxy does not match with version in release this repo

### ISSUE THREAD

**Issue by patsevanton** [pgkehle/ansible-mongodb#11]
Hello!
Thanks for role!

![image](https://user-images.githubusercontent.com/10828883/162610950-c8adbc61-ba82-4b4d-82cd-2ab87c718959.png)
and

![image](https://user-images.githubusercontent.com/10828883/162610983-bdc22a3f-504b-4bd3-8ad8-e7f5bd1a7d1c.png)

Could you synchonize version and code?
Thanks!

**Comment by isaackehle** [comment]
I've deprecated `pgkehle.mongodb` for [isaackehle.mongodb](https://galaxy.ansible.com/isaackehle/ansible_mongodb)
